version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14      

  pre_build:
    commands:
      - mkdir output

  build:
    commands:
      - node -v
      - npm ci
      - npm run build

artifacts:
  files:
    - '**/*'

    