version: 0.2

phases:
  install:
    commands:
      - node -v
      - npm install

  pre_build:
    commands:
      - mkdir output

  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'

    